# Generated by Django 5.1.4 on 2025-01-13 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Ф.И.О Хирурга')),
            ],
            options={
                'verbose_name': 'Хирург',
                'verbose_name_plural': 'Хирурги',
            },
        ),
        migrations.CreateModel(
            name='SurgeryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=255, verbose_name='Название oперация')),
            ],
            options={
                'verbose_name': 'Название операции',
                'verbose_name_plural': 'Название операции',
            },
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='Название типа oперация')),
            ],
            options={
                'verbose_name': 'Тип операции',
                'verbose_name_plural': 'Тип операции',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('админ', 'админ'), ('заведующий', 'заведующий')], default='заведующий', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('branch_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19')], verbose_name='Номер отдела')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL, verbose_name='Заведующи')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отдели',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О пациента')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('diagnost', models.CharField(max_length=255, verbose_name='Диагност')),
                ('date_of_surgery', models.DateTimeField(verbose_name='Дата операции')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='backend.branch', verbose_name='Oтдел')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='backend.surgeon')),
                ('surgery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='backend.surgeryname')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='backend.surgerytype')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
