# Generated by Django 5.1.4 on 2025-01-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryname',
            name='surgery_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название oперация'),
        ),
        migrations.AlterField(
            model_name='surgerytype',
            name='type_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название типа oперация'),
        ),
    ]
