# Generated by Django 5.1.4 on 2025-01-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_surgeryname_surgery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='seq_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
