# Generated by Django 5.1.4 on 2025-01-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_surgery_seq_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='surgery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='backend.surgerytype'),
        ),
    ]
