# Generated by Django 5.1.4 on 2025-01-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_surgery_surgery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('editable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='date_of_surgery',
        ),
    ]
