# Generated by Django 5.1.4 on 2025-01-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_surgeryday_remove_surgery_date_of_surgery'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='date_of_surgery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='backend.surgeryday', verbose_name='Дата операции'),
        ),
    ]
