# Generated by Django 5.1.4 on 2025-01-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_surgery_date_of_surgery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryday',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата операции'),
        ),
    ]
