# Generated by Django 5.1.4 on 2025-01-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_surgeryday_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь (Заведующий)', 'verbose_name_plural': 'Пользователи (Заведующии)'},
        ),
        migrations.AlterModelOptions(
            name='surgeryday',
            options={'verbose_name': 'День операции', 'verbose_name_plural': 'День операции'},
        ),
        migrations.AlterModelOptions(
            name='surgerytype',
            options={'verbose_name': 'Тип операции (Примечания)', 'verbose_name_plural': 'Тип операции (Примечания)'},
        ),
        migrations.AddField(
            model_name='surgeon',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeons', to='backend.branch', verbose_name='Отделение'),
        ),
    ]
