# Generated by Django 5.1.4 on 2025-01-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_customuser_options_alter_surgeryday_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='surgeon',
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgeon',
            field=models.ManyToManyField(related_name='surgeries', to='backend.surgeon'),
        ),
    ]
