# Generated by Django 5.1.4 on 2025-01-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_surgery_surgeon_surgery_surgeon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgery',
            old_name='surgeon',
            new_name='surgeons',
        ),
    ]
