# Generated by Django 5.1.1 on 2025-01-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_surgeon_surgery_surgeons'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='own_branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='own_branchs_surgeries', to='backend.branch', verbose_name='Древний Oтдел'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
