# Generated by Django 5.1.1 on 2025-01-21 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_surgery_own_branch_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='head',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='heads', to='backend.branch'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='diagnost',
            field=models.CharField(max_length=255, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='own_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_branchs_surgeries', to='backend.branch', verbose_name='Древний Oтдел'),
        ),
    ]
