# Generated by Django 5.1.1 on 2025-01-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_branch_head_customuser_branches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgeon',
            old_name='branch',
            new_name='branche',
        ),
    ]
