# Generated by Django 5.1.1 on 2025-01-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_branch_surgeon_branche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeon',
            name='branche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeon', to='backend.branch', verbose_name='Отделение'),
        ),
    ]
