# Generated by Django 5.1.1 on 2025-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_surgeon_branche'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeon',
            name='branch',
            field=models.ManyToManyField(related_name='surgeons', to='backend.branch', verbose_name='Отделении'),
        ),
    ]
