# Generated by Django 5.1.1 on 2025-01-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_surgeon_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgeon',
            name='branche',
        ),
    ]
