# Generated by Django 5.1.4 on 2025-02-05 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_surgeon_branche'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgerySurgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.surgeon')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.surgery')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
