# Generated by Django 5.1.4 on 2025-02-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_surgerysurgeon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='surgeons',
            field=models.ManyToManyField(related_name='surgerie', to='backend.surgeon'),
        ),
    ]
