# Generated by Django 5.1.4 on 2025-02-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_surgery_surgeons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgery',
            old_name='surgeons',
            new_name='surgeons1',
        ),
    ]
