# Generated by Django 5.1.4 on 2025-02-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_surgeons_surgery_surgeons1'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='surgeons',
            field=models.ManyToManyField(related_name='surgeries', through='backend.SurgerySurgeon', to='backend.surgeon'),
        ),
    ]
