# Generated by Django 5.1.1 on 2025-07-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_surgery_surgeons'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='page_number',
            field=models.IntegerField(default=1, verbose_name='Номер страницы'),
            preserve_default=False,
        ),
    ]
