# Generated by Django 5.1.1 on 2025-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_branch_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Например: "A(II) Rh+ + комментарий"', max_length=128, null=True, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='page_number',
            field=models.IntegerField(default=1, verbose_name='Номер страницы'),
        ),
    ]
